spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fingertop/config-repo.git
          username: username
          password: password
server:
  port: 1201


#比如，要访问master分支，config-client应用的dev环境，就可以访问这个url：
#http://localhost:1201/config-client/dev/master

#/{application}/{profile}[/{label}]
#/{application}-{profile}.yml
#/{label}/{application}-{profile}.yml
#/{application}-{profile}.properties
#/{label}/{application}-{profile}.properties

#配置在yml，这样config-server中的配置信息才能被其他应用正确加载。
